### ISSUE TITLE
Identify and fix CI testing problem re #36

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#43]
(affects #36)

patch https://github.com/abebeos/SearchSECOController/commit/7909b2ae9798ba9948ed5ee86ae2f81886e87669 fixes test-failures #36 locally on both, windows and ubuntu.

The (quite hidden) problem is that the tests still fail on the github CI

https://github.com/abebeos/SearchSECOController/actions/runs/3248492973/jobs/5329768236

identify and fix the problem (this could be github related, too)

## 

- [x] #47 (additional problem)

## Follow-Up Issues

* provide deterministic build/test processes, ideally across OSs

**Comment by abebeos** [comment]
Root cause:

Github has an updated version of git

https://github.com/SecureSECO/SearchSECOController/actions/runs/3161077512/jobs/5146261864#step:2:17

This version has a different behavior for spare-checkouts, leading to the following:

- the repo checkout contains more files than it should, leading to test-failures.

**Comment by abebeos** [comment]
In order to reproduce locally, ensure that you have a new git version (>= 2.37.3)

**Comment by abebeos** [comment]
After updating local machine getting now a concrete error-messages from git:

Download Command: git clone https://github.com/git-tips/tips "temp" --no-checkout --quiet && cd "temp" && git sparse-checkout set *.c *.cpp *.h *.cs *.cc *.hpp *.java *.py *.js --quiet && git config core.autocrlf true
```
fatal: specify directories rather than patterns.  If your directory really has any of '*?[]\' in it, pass --skip-checks
```
This should not be fixed in a "quick-n-dirty" way, it needs its "own night":

https://github.com/SecureSECO/SearchSECOSpider/issues/17

**Comment by slingerbv** [comment]
Any possibility to do this more elegantly? I'd rather not fall back.

Excellent analysis, nonetheless!

**Comment by abebeos** [comment]
first step would be to the mentioned "provide deterministic build/test processes, ideally across OSs", because debugging this in your current system was a nightmare.

The the usual "look for ready build libraries", "refactor/rework code for maintainability" etc.

All is more or less standard-procedure (at least for me, coming from hardware-design).

Summarized within #41 

The most difficult thing with this is motivation, and keeping "the flow" up (highest mental throughput. Bad thing: i loose sense of time, one day without responses can feel like a week. Especially when waiting for stuff on project resources.

Would need at minimum: access to issue-triage, and ideally merge-rights (at least for development branch). Then what remains is that you process issues-to-gitcoin quickly.

**Comment by abebeos** [comment]
> Excellent analysis

No need for nice words.

Nice actions are more effective: add the requested bounty ($300, https://github.com/SecureSECO/SearchSECOController/issues/36#issuecomment-1279371207)

**Comment by abebeos** [comment]
> Any possibility to do this more elegantly? I'd rather not fall back.

File a follow-up issue.
