### ISSUE TITLE
[REMINDER] Bounty Payout

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#51]
The first chunk of work contained the following bounties:

- $300 - https://gitcoin.co/issue/29454
- $100 - https://gitcoin.co/issue/29420

The bounties are still unpaid.

To my knowledge, the Paypal-bound bounties are not paid out by gitcoin, but by the bounty issuer, so any technical problems on gitcoin would not justify payout delays.

Gitcoin support: `support at gitcoin dot co`

## unfiled bounties

This bounty remained unprocessed (which means: I was faster in fixing bugs than the project-lead in filing/paying bounties).

The process here is simple: you reopen the issue and apply bounty, I start, you accept, I post the result and close the issue, and you payout:

- $300 - https://github.com/SecureSECO/SearchSECOController/issues/43

## SecureSECO Project Handbook

( a draft text for bounty processing within the project )

saved text for later processing

**Comment by slingerbv** [comment]
Bounty paid through your preferred method. Will reply to other things later.

**Comment by abebeos** [comment]
> Bounty paid through your preferred method.

Yes, confirmed, thank you!

> Will reply to other things later.

No replies needed from my side, I should be good till end of week.
