### ISSUE TITLE
Provide Architectural Overview,  Validate Naming

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#55]
(task partially fulfilled)

A simplified textual Architectural Overview should be derived from existing material. During the process, inconsistencies should be detected. This task is naturally executed by an analyst entering the project (e.g.  depends on this overview to understand the system).

The simplified overview is used e.g. to allow bounty-workers to understand the system fast, allowing this way low-budget issues/bounties. Once stabilized, it can be used to create graphical overviews (both, standard UML for techs and "fancy-visuals" for material like websites etc.)

### SecureSECO - Secure Software ECOsystem

```
SecureSECO - Docker Compose based runtime, integrates all other subsystems, including web ui
  ...
  ...
  SearchSECOPortal


[CLIENT]
SearchSECOController - Executable that integrates Crawler/Spider/Parser
  SearchSECOCrawler
  SearchSECOSpider
  SearchSECOParser


[SERVER] - Scalable Database, Centralized
SearchSECODatabaseAPI
  


TrustSECO
  TrustSECO-Portal
  TrustSECO-Spider
  TrustSECO-DLT

FAIRSECO
  (planning phase)
```

## Naming

| Current Name | Functionality | Suggested/Normalized Name |
| - | - | - |
| SearchSECOController | Client Lib/CLI | SearchSECOClient |
| SearchSECODatabaseAPI | Database Server Node | SearchSECODatabase / SearchSECODatabaseNode |

## Inconsistencies

* SearchSECOPortal vs. TrustSECO-Portal (hyphen)
* SearchSECOSpider vs. TrustSECO-Spider (hyphen)
* 
## Existent Material

* https://github.com/SecureSECO/SearchSECOController/blob/master/Documentation/Documentation.pdf
  * Page 3

## Organizational
Moving this to Batch 22.02.

**Comment by slingerbv** [comment]
Please note that in the middle-to-long term we want to go to one project, perhaps with subprojects for the database and stuff. In this way, we don't get so many convoluted commits. The SecureSECO project is the umbrella project.

**Comment by abebeos** [comment]
(this here is not about repo organization)

**Comment by abebeos** [comment]
> Please note that in the middle-to-long term we want to go to one project

first step would be #64
