### ISSUE TITLE
[CRITICAL] Provide Documentation for the Server

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#74]
(draft)

- beyond scope of #55 
- blocks #72 and others

## Intro

Limited work on #55 shows that the system is in essence a Client/Server one.

The Client (SearchSECOController) is well documented.

The Server (it looks like `SearchSECODatabaseAPI`) has limited documentation, especially the physically deployed server.

## Requirements/Questions

- What software runs on the server?
- Is this a cluster-configuration?
- Are the "live" configuration-files available in a public repo?
- is SSH access available on request?
- ...

Please not that it is impossible to debug the system if "The Sever" or "The Database" is a black box.

## Organizational
Moving this to Batch 22.02.

**Comment by slingerbv** [comment]
We run three separate Ubuntu vhost servers from the university. We haven't done much more than follow [the instructions on the DB API](https://github.com/SecureSECO/SearchSECODatabaseAPI). 

There is no cluster, just those three vhosts. There is one more vhost that runs the web server.

We have no configuration files, besides the docker stuff. What are you looking for in particular?

SSH will not be available. It's probably best to deploy a DB yourself in a local docker image and see if you can get it to work against your own client. 

@ElenaBaninemeh is this complete? Did you do anything else to configure these servers?

**Comment by abebeos** [comment]
The information you gave me is ok, I should be covered. Just one thing:

> SSH will not be available.

This is a must, especially if you want to safe the existent database (if e.g. corrupted data is the RCoF. If the existent data is not of much relevance for you, than all is good.

Minimum access needed would be: the directory with the log-files. Though a log-file-zip upload somewhere to download should be initially enough.
