### ISSUE TITLE
Provide a Method for quasi-native ubuntu debugging on Windows

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#77]
(spawned by #35)

It is difficult to debug issues that occur only on ubuntu (either native, or within docker) and not on windows.

A method should be provided to allow debugging of ubuntu on a windows-machine (for the reason that it is commonly used).

**Main Requirement:** very easy to setup

(The alternative would be to setup ubuntu as a dual-boot or on a 2nd dev machine)

### Solution Paths

* docker + vscode + debug logs => no decent debugger
* WSL2 + VSCode => couldn't get it functional, additionally: WSL2 mem-hungry
* WSL2 + VS2022 => complex instructions, possibly similar to VSCode
* trying now: HyperV Ubuntu Instance
  * [x] setup: ok
  * [x] verify if bug happens: yes
  * [x] setup IDE for debugging

### Suggested: Hyper-V

* create an ubuntu 20.04 (this is including a GUI)
  * avoid "quick-create", as the disk size is quite low.
* install Visual Studio Code
  * install C++ and cmake utils
* install packages as usual via sudo apt (including docker)
* => do the debugging

#### Fall Back

* add ubuntu dual-boot on backup pc

**Comment by slingerbv** [comment]
I know Xendarboh is a total docker-wizard, he solves it that way, by just spawning dockers on his local machine.

**Comment by abebeos** [comment]
(I failed yesterday with docker, though I use docker nearly daily. Additionally, the solution must be simple and easy to setup, thus one can throw it at junior devs).

**Comment by abebeos** [comment]
The bug happens on an Hyper-V ubuntu instance, too, so it can be used for debugging (no native-machine setup needed).
