### ISSUE TITLE
[CRITICAL] Update srcML to a newer version

### ISSUE THREAD

**Issue by abebeos** [SecureSECO/SearchSECOController#83]
(re #82, #79)

Version 1.0 of srcML is currently used.

Several problems could simply be a result of problems within this early version of srcML

Update to a newer version.

Note that this can introduce side-effects.

- [x] Read through srcml repos, try docker builds etc.
  - => for now too complex, a major future task
- [x] use latest https://github.com/srcML/srcMLReleases/raw/main/srcml_1.0.0-1_ubuntu20.04.deb

**Comment by slingerbv** [comment]
There is no newer version, unfortunately.

**Comment by abebeos** [comment]
(there is one, but I'm close to an overload, so I cannot comment/explain more or workflow at this moment)

**Comment by abebeos** [comment]
Staying for now with the update to latest:

https://github.com/srcML/srcMLReleases/raw/main/srcml_1.0.0-1_ubuntu20.04.deb

## Followup

#84
